"""Static favicon routes for the Streamable HTTP transport.

The Claude connector-list icon is rendered from Google's favicon service
keyed off the connector's domain
(``https://www.google.com/s2/favicons?domain=mcp.example.com``), NOT from the
MCP ``icons`` field. Google's crawler fetches ``/favicon.ico`` (and parses any
``<link rel="icon">`` on ``/``), so the HTTP transport serves the rasterized
clickwheel mark at those paths.

These routes are registered on the FastMCP app at import time; they're inert
under stdio (no HTTP server) and only matter behind the tunnel. The matching
Cloudflare Access *bypass* for ``/favicon.ico`` is what lets Google's
unauthenticated crawler reach them — see docs/mcp/remote-mobile-access*.md.

Asset bytes are generated by ``scripts/generate-favicon.sh`` from the same SVG
mark as ``SERVER_ICON``; this module only reads and serves them.
"""

from __future__ import annotations

from functools import cache
from importlib.resources import files

# Served paths -> (asset filename, content type). Order is cosmetic.
_ASSETS: dict[str, tuple[str, str]] = {
    "/favicon.ico": ("favicon.ico", "image/x-icon"),
    "/favicon.svg": ("favicon.svg", "image/svg+xml"),
    "/favicon-32.png": ("favicon-32.png", "image/png"),
    "/apple-touch-icon.png": ("apple-touch-icon.png", "image/png"),
}

# A tiny landing page so a human (or the favicon crawler) hitting the apex
# finds the icon link rather than a bare 404.
_INDEX_HTML = (
    "<!doctype html><html><head><meta charset=utf-8>"
    "<title>clickwheel</title>"
    '<link rel="icon" type="image/svg+xml" href="/favicon.svg">'
    '<link rel="icon" href="/favicon.ico">'
    '<link rel="apple-touch-icon" href="/apple-touch-icon.png">'
    "</head><body>clickwheel MCP server.</body></html>"
)

# Long cache: the asset only changes when the mark does (rare), and Google's
# crawler benefits from a stable, cacheable response.
_CACHE_CONTROL = "public, max-age=86400"


@cache
def _asset_bytes(filename: str) -> bytes:
    return (files("clickwheel.mcp") / "assets" / filename).read_bytes()


def register_http_assets(mcp) -> None:
    """Attach favicon + index routes to the FastMCP HTTP app."""
    from starlette.requests import Request
    from starlette.responses import HTMLResponse, Response

    def _make_handler(filename: str, content_type: str):
        async def handler(_request: Request) -> Response:
            return Response(
                content=_asset_bytes(filename),
                media_type=content_type,
                headers={"Cache-Control": _CACHE_CONTROL},
            )

        return handler

    for path, (filename, content_type) in _ASSETS.items():
        mcp.custom_route(path, methods=["GET"], include_in_schema=False)(
            _make_handler(filename, content_type)
        )

    @mcp.custom_route("/", methods=["GET"], include_in_schema=False)
    async def _index(_request: Request) -> Response:
        return HTMLResponse(_INDEX_HTML, headers={"Cache-Control": _CACHE_CONTROL})
