version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/Los_Angeles'
  - package-ecosystem: 'npm'
    directory: '/web'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '06:00'
      timezone: 'America/Los_Angeles'
  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '06:00'
      timezone: 'America/Los_Angeles'
  - package-ecosystem: 'npm'
    directory: '/tools/ci'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '06:00'
      timezone: 'America/Los_Angeles'
