#!/usr/bin/env python3
"""Generate the per-section CLI reference pages from the Typer app.

Writes one page per command group under docs-mintlify/reference/cli/ (library,
playlists, ipod, plex, apple-music, lastfm) by introspecting clickwheel's
Typer/Click command tree, so the reference can't drift from the actual commands.
Recurses into sub-apps (e.g. `plex`, `apple`) and groups commands by their Typer
`rich_help_panel` (the same grouping shown in `clickwheel --help`). The CLI
landing page (reference/cli.mdx) is hand-written and not touched here. Run via
`make docs-reference`; CI ("Docs Reference Freshness") regenerates and fails if
the committed output differs.

Usage: python scripts/gen-cli-reference.py
"""

from __future__ import annotations

import pathlib

import click
import typer.main
from cli_examples import EXAMPLES

from clickwheel.cli import app

OUT_DIR = pathlib.Path("docs-mintlify/reference/cli")

# Panel -> (filename slug, render order). Panels not listed are skipped with a
# warning so a new, untagged command never disappears silently.
SECTIONS = [
    ("Library", "library"),
    ("Playlists", "playlists"),
    ("iPod", "ipod"),
    ("Plex", "plex"),
    ("Apple Music", "apple-music"),
    ("Last.fm", "lastfm"),
]
FALLBACK_SECTION = "Other"


def _header(section: str) -> str:
    return (
        "---\n"
        f"title: {section}\n"
        f"sidebarTitle: {section}\n"
        f"description: clickwheel {section} commands and their options.\n"
        "---\n\n"
        "{/* GENERATED by scripts/gen-cli-reference.py, do not edit by hand. */}"
    )


_TYPE_NAMES = {
    "text": "string",
    "integer": "integer",
    "float": "number",
    "boolean": "boolean",
}


def _param_type(p: click.Parameter) -> str:
    if getattr(p, "is_flag", False):
        return "boolean"
    name = getattr(getattr(p, "type", None), "name", "") or ""
    return _TYPE_NAMES.get(name, "string")


def _param_fields(cmd: click.Command) -> list[str]:
    """Render each option/argument as a <ParamField> block."""
    ctx = click.Context(cmd, info_name=cmd.name)
    out: list[str] = []
    for p in cmd.get_params(ctx):
        if p.name == "help":
            continue
        attrs = f'path="{", ".join(p.opts)}" type="{_param_type(p)}"'
        if p.required:
            attrs += " required"
        if p.default not in (None, False, ""):
            attrs += f' default="{p.default}"'
        desc = (getattr(p, "help", None) or "").strip()
        out.extend(["", f"<ParamField {attrs}>", f"  {desc}", "</ParamField>"])
    return out


def _examples_block(path: str) -> list[str]:
    """Render the curated Examples block for a command, if any."""
    examples = EXAMPLES.get(path)
    if not examples:
        return []
    out = ["**Examples**", "", "```bash"]
    for i, (command, comment) in enumerate(examples):
        if i:
            out.append("")
        if comment:
            out.append(f"# {comment}")
        out.append(command)
    out.extend(["```", ""])
    return out


def _collect(
    group: click.Group, prefix: str, inherited: str
) -> list[tuple[str, str, click.Command]]:
    """Return (section, command path, leaf command), recursing into sub-groups.

    A sub-group's subcommands inherit the group's panel as their section.
    """
    leaves: list[tuple[str, str, click.Command]] = []
    for name, sub in group.commands.items():
        if sub.hidden:
            continue
        path = f"{prefix}{name}"
        section = getattr(sub, "rich_help_panel", None) or inherited or FALLBACK_SECTION
        # Typer's TyperGroup doesn't reliably pass isinstance(click.Group), so
        # detect sub-apps by the presence of a populated `.commands` dict.
        if getattr(sub, "commands", None):
            leaves.extend(_collect(sub, f"{path} ", section))
        else:
            leaves.append((section, path, sub))
    return leaves


def _render_section(commands: list[tuple[str, click.Command]], section: str) -> str:
    lines = [_header(section)]
    # Heading shows the leaf name (the page title supplies the Plex/Apple
    # context); the synopsis keeps the full invocation path.
    for path, cmd in sorted(commands, key=lambda pc: pc[1].name):
        lines.append(f"\n## `{cmd.name}`\n")
        ctx = click.Context(cmd, info_name=cmd.name)
        pieces = " ".join(cmd.collect_usage_pieces(ctx))
        synopsis = f"clickwheel {path}" + (f" {pieces}" if pieces else "")
        lines.extend(["```bash", synopsis, "```", ""])
        help_text = (cmd.help or cmd.short_help or "").strip()
        if help_text:
            lines.append(help_text + "\n")
        lines.extend(_examples_block(path))
        lines.extend(_param_fields(cmd))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    root = typer.main.get_command(app)
    leaves = _collect(root, "", FALLBACK_SECTION)

    by_section: dict[str, list[tuple[str, click.Command]]] = {}
    for section, path, cmd in leaves:
        by_section.setdefault(section, []).append((path, cmd))

    known = {name for name, _ in SECTIONS}
    for section in by_section:
        if section not in known:
            print(f"WARNING: commands in untagged panel {section!r} were skipped")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for section, slug in SECTIONS:
        commands = by_section.get(section)
        if not commands:
            continue
        out = OUT_DIR / f"{slug}.mdx"
        out.write_text(_render_section(commands, section))
        print(f"wrote {out} ({len(commands)} commands)")


if __name__ == "__main__":
    main()
