#!/usr/bin/env python3
"""Generate the docs changelog from the repo's CHANGELOG.md.

Reads CHANGELOG.md (maintained by release-please from Conventional Commits) and
writes docs-mintlify/changelog.mdx as a series of Mintlify <Update> blocks — so
the docs changelog can't drift from the real release history. Run via
`make docs-reference`; CI ("Docs Reference Freshness") regenerates and fails if
the committed output differs.

Usage: python scripts/gen-changelog.py
"""

from __future__ import annotations

import pathlib
import re

SRC = pathlib.Path("CHANGELOG.md")
OUT = pathlib.Path("docs-mintlify/changelog.mdx")

HEADER = """\
---
title: Changelog
description: clickwheel release history.
---

{/* GENERATED by scripts/gen-changelog.py from CHANGELOG.md, do not edit by hand. */}

Releases are produced automatically by
[release-please](https://github.com/googleapis/release-please) from
[Conventional Commits](https://www.conventionalcommits.org/). Full notes also
live on [GitHub Releases](https://github.com/pdugan20/clickwheel/releases).
"""

# ## [0.16.0](https://github.com/.../compare/v0.15.1...v0.16.0) (2026-05-30)
HEADING = re.compile(
    r"^##\s+\[(?P<ver>[^\]]+)\]\((?P<url>[^)]+)\)\s+\((?P<date>[^)]+)\)\s*$"
)


def _sections(text: str) -> list[tuple[str, str, str, str]]:
    """Return (version, url, date, body) per release, newest first."""
    lines = text.splitlines()
    out: list[tuple[str, str, str, str]] = []
    current: tuple[str, str, str] | None = None
    body: list[str] = []

    def flush() -> None:
        if current is not None:
            ver, url, date = current
            out.append((ver, url, date, "\n".join(body).strip()))

    for line in lines:
        m = HEADING.match(line)
        if m:
            flush()
            current = (m["ver"], m["url"], m["date"])
            body = []
        elif current is not None:
            body.append(line)
    flush()
    return out


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    blocks = [HEADER]
    for ver, url, date, body in _sections(text):
        blocks.append(
            f'\n<Update label="{ver}" description="{date}">\n\n'
            f"{body}\n\n"
            f"[Compare on GitHub]({url})\n\n"
            f"</Update>\n"
        )
    OUT.write_text("".join(blocks), encoding="utf-8")
    print(f"Wrote {OUT} ({len(blocks) - 1} releases)")


if __name__ == "__main__":
    main()
