#!/usr/bin/env python3
"""Generate the per-domain MCP tool reference pages from the FastMCP instance.

Writes one page per domain under docs-mintlify/reference/mcp-tools/ (library,
playlists, ipod, plex, apple-music, lastfm) by introspecting the registered
tools (name, description, input schema), grouped by source module, so a new tool
shows up automatically and the reference can't drift from the code. The MCP
landing page (reference/mcp-tools.mdx) is hand-written and not touched here. Run
via `make docs-reference`; CI ("Docs Reference Freshness") regenerates and fails
if the committed output differs.

Usage: python scripts/gen-mcp-reference.py   (needs the [mcp] extra installed)
"""

from __future__ import annotations

import pathlib

# Importing the server registers every tool on the shared FastMCP instance.
from mcp_examples import PROMPTS

from clickwheel.mcp import server as _server  # noqa: F401
from clickwheel.mcp._runtime import mcp

OUT_DIR = pathlib.Path("docs-mintlify/reference/mcp-tools")

# Source module key -> friendly domain label.
DOMAINS = {
    "library": "Library",
    "playlist": "Playlists",
    "ipod": "iPod",
    "plex": "Plex",
    "apple": "Apple Music",
    "scrobble": "Last.fm",
}

# Domain label -> (filename slug), in render order. Labels not listed are
# skipped with a warning so a new tool module never disappears silently.
SECTIONS = [
    ("Library", "library"),
    ("Playlists", "playlists"),
    ("iPod", "ipod"),
    ("Plex", "plex"),
    ("Apple Music", "apple-music"),
    ("Last.fm", "lastfm"),
]


def _header(label: str) -> str:
    return (
        "---\n"
        f"title: {label}\n"
        f"sidebarTitle: {label}\n"
        f"description: clickwheel MCP server tools for {label}.\n"
        "---\n\n"
        "{/* GENERATED by scripts/gen-mcp-reference.py, do not edit by hand. */}"
    )


def _module_key(fn) -> str:
    return getattr(fn, "__module__", "").rsplit(".", 1)[-1]


def _first_paragraph(text: str | None) -> str:
    if not text:
        return ""
    return text.strip().split("\n\n", 1)[0].replace("\n", " ").strip()


def _params(schema: dict) -> list[str]:
    """Render each tool input as a <ParamField> block."""
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    out: list[str] = []
    for name, spec in props.items():
        if name == "ctx":
            continue
        typ = spec.get("type") or ("any" if spec.get("anyOf") else "string")
        if typ == "array":
            items = (spec.get("items") or {}).get("type")
            typ = f"{items}[]" if items else "array"
        attrs = f'path="{name}" type="{typ}"'
        if name in required:
            attrs += " required"
        if spec.get("default") not in (None, "", False):
            attrs += f' default="{spec["default"]}"'
        desc = (spec.get("description") or "").replace("\n", " ").strip()
        out.extend(["", f"<ParamField {attrs}>", f"  {desc}", "</ParamField>"])
    return out


def _render_section(tools: list, label: str) -> str:
    lines = [_header(label)]
    prompts = PROMPTS.get(label)
    if prompts:
        lines.append("\n**Try asking Claude**\n")
        lines.extend(f'- _"{p}"_' for p in prompts)
    for tool in sorted(tools, key=lambda t: t.name):
        lines.append(f"\n## `{tool.name}`\n")
        desc = _first_paragraph(tool.description)
        if desc:
            lines.append(desc + "\n")
        lines.extend(_params(tool.parameters))
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    tools = mcp._tool_manager.list_tools()
    grouped: dict[str, list] = {}
    for tool in tools:
        label = DOMAINS.get(_module_key(tool.fn), _module_key(tool.fn).title())
        grouped.setdefault(label, []).append(tool)

    known = {label for label, _ in SECTIONS}
    for label in grouped:
        if label not in known:
            print(f"WARNING: tools in untagged domain {label!r} were skipped")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for label, slug in SECTIONS:
        domain_tools = grouped.get(label)
        if not domain_tools:
            continue
        out = OUT_DIR / f"{slug}.mdx"
        out.write_text(_render_section(domain_tools, label))
        print(f"wrote {out} ({len(domain_tools)} tools)")


if __name__ == "__main__":
    main()
