#!/usr/bin/env python3
"""Generate the MCP tool reference from the FastMCP instance.

Writes docs-mintlify/reference/mcp-tools.mdx by introspecting the registered
tools (name, description, input schema) — grouped by the source module, so a new
tool shows up automatically and the reference can't drift from the code. Run via
`make docs-reference`; CI ("Docs Reference Freshness") regenerates and fails if
the committed output differs.

Usage: python scripts/gen-mcp-reference.py   (needs the [mcp] extra installed)
"""

from __future__ import annotations

import pathlib

# Importing the server registers every tool on the shared FastMCP instance.
from clickwheel.mcp import server as _server  # noqa: F401
from clickwheel.mcp._runtime import mcp

OUT = pathlib.Path("docs-mintlify/reference/mcp-tools.mdx")

# Friendly group labels by source module; unknown modules fall back to the
# capitalized module name, so new tool modules still appear.
DOMAINS = {
    "library": "Library",
    "playlist": "Playlists",
    "ipod": "iPod",
    "plex": "Plex",
    "apple": "Apple Music",
    "scrobble": "Last.fm",
}

HEADER = """\
---
title: MCP tool reference
description: Every tool the clickwheel MCP server exposes.
---

{/* GENERATED by scripts/gen-mcp-reference.py — do not edit by hand. */}

The clickwheel MCP server exposes these tools to Claude and other MCP clients.
See [MCP server](/concepts/mcp-server) for setup. Each tool wraps the same core
logic as the CLI.
"""


def _module_key(fn) -> str:
    return getattr(fn, "__module__", "").rsplit(".", 1)[-1]


def _first_paragraph(text: str | None) -> str:
    if not text:
        return ""
    return text.strip().split("\n\n", 1)[0].replace("\n", " ").strip()


def _params(schema: dict) -> list[str]:
    props = (schema or {}).get("properties", {})
    required = set((schema or {}).get("required", []))
    if not props:
        return []
    rows = [
        "",
        "| Parameter | Type | Required | Description |",
        "| --- | --- | --- | --- |",
    ]
    for name, spec in props.items():
        if name == "ctx":
            continue
        typ = spec.get("type") or ("any" if spec.get("anyOf") else "")
        req = "yes" if name in required else "no"
        desc = (spec.get("description") or "").replace("\n", " ").strip()
        rows.append(f"| `{name}` | {typ} | {req} | {desc} |")
    return rows if len(rows) > 3 else []


def render() -> str:
    tools = mcp._tool_manager.list_tools()
    grouped: dict[str, list] = {}
    for tool in tools:
        key = _module_key(tool.fn)
        grouped.setdefault(key, []).append(tool)

    lines = [HEADER, f"\n{len(tools)} tools across {len(grouped)} domains.\n"]
    for key in sorted(grouped, key=lambda k: DOMAINS.get(k, k)):
        label = DOMAINS.get(key, key.replace("_", " ").title())
        lines.append(f"\n## {label}\n")
        for tool in sorted(grouped[key], key=lambda t: t.name):
            lines.append(f"### `{tool.name}`\n")
            desc = _first_paragraph(tool.description)
            if desc:
                lines.append(desc + "\n")
            lines.extend(_params(tool.parameters))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
